language: python

dist: xenial

services:
  - xvfb

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install sympy
  - pip install nose2

script:
  - nose2
